### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yangguanxun** [kbatsos/CBMV#7]
配置好环境之后，如何实现这个项目？？？？？？ 望大神不吝赐教

**Comment by kbatsos** [comment]
Please follow the instruction on README

**Comment by yangguanxun** [comment]
scipy的版本也有要求吗

**Comment by kbatsos** [comment]
sklearn (version 0.17.1). Please read the README. scipy recent should work

**Comment by ccj5351** [comment]
> 配置好环境之后，如何实现这个项目？？？？？？ 望大神不吝赐教

Yes. Just follow the **Compilation** section to compile the code, and then **Training** section for random forest training and **Disparity Estimation** section for disparity map as output.

**Comment by ccj5351** [comment]
We specify the **sklearn** as version 0.17.1, it is because that the model we provided here is trained in this setting. If you use newer version **sklearn** to load our model, there might exist some problems. But you can always use new version sklearn as long as the training and testing both using this version.

**Comment by yangguanxun** [comment]
这种问题该如何解决
 Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from train import Training as cbmvtrain
  File "./train.py", line 25, in <module>
    import librectification as rect
ImportError: No module named librectification

**Comment by kbatsos** [comment]
Go to the cpp folder and compiler the relevant libraries. The instructions are on the README please follow the instructions.

**Comment by kbatsos** [comment]
If you don't want to use a GPU, don't compile post and also remove the post processing pipeline from the python code.
